force-app/main/default/objects/Sensor__c/fields/Max_Vectors_Length__c.field-meta.xml
<CustomField>
    <fullName>Max_Vectors_Length__c</fullName>
    <label>Max Vectors Length</label>
    <summarizedField>Sensor_Event__c.Modulus_Vector_Length__c</summarizedField>
    <summaryForeignKey>Sensor_Event__c.Sensor__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <label>Sensor Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/X_Number__c.field-meta.xml
<CustomField>
    <fullName>X_Number__c</fullName>
    <label>X Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Y_Number__c.field-meta.xml
<CustomField>
    <fullName>Y_Number__c</fullName>
    <label>Y Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Z_Number__c.field-meta.xml
<CustomField>
    <fullName>Z_Number__c</fullName>
    <label>Z Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorController.cls
public with sharing class SensorController {
    static Integer PAGE_SIZE = 6;

    @AuraEnabled(cacheable=true)
    public static  List<Sensor__c> getSensorList() {
        List<Sensor__c> sensors = [SELECT Name,
            Max_Vectors_Length__c 
            FROM Sensor__c 
            LIMIT 10];
        return sensors;
    }

    @AuraEnabled(cacheable=true)
    public static PageResult getSensorEventTileList(String sensorId, Integer pageNumber){
        Integer pageSize = SensorController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PageResult result = new PageResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        result.totalItemCount = Database.countQuery(
            'SELECT count() FROM Sensor_Event__c WHERE Sensor__c =:sensorId'
        );
        result.records = Database.query(
            'SELECT Name, Sensor__c, X_Number__c, Y_Number__c, Z_Number__c FROM Sensor_Event__c WHERE Sensor__c =:sensorId ORDER BY Name LIMIT :pageSize OFFSET :offset'
        );
        System.debug('my result ------ ' + result);
        return result;
    }
}