force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <label>Sensor Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/X_Number__c.field-meta.xml
<CustomField>
    <fullName>X_Number__c</fullName>
    <label>X Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Y_Number__c.field-meta.xml
<CustomField>
    <fullName>Y_Number__c</fullName>
    <label>Y Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sensor_Event__c/fields/Z_Number__c.field-meta.xml
<CustomField>
    <fullName>Z_Number__c</fullName>
    <label>Z Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SensorEventService.cls
@RestResource(urlMapping='/sensorEvents/*')
global with sharing class SensorEventService {

    @HttpPost
    global static void doPost() {
        RestRequest req = RestContext.request;
        String sensorData = req.requestBody.toString();
        SensorDataWrapper data = (SensorDataWrapper) JSON.deserialize(sensorData, SensorDataWrapper.class);
        List<Sensor__c> sensors = [SELECT Id FROM Sensor__c WHERE Name = :data.sensorid LIMIT 1];
        Sensor__c sensor;
        if (sensors.isEmpty()) {
            sensor = new Sensor__c(Name = 'Created from Postman ' + data.sensorid);
            insert sensor;
        } else {
            sensor = sensors[0];
        }

        List<Sensor_Event__c> sensorEvents = new List<Sensor_Event__c>();
        for (SensorDataWrapper.Vector vector : data.vectors) {
            Sensor_Event__c event = new Sensor_Event__c(
                Name = 'Sensor Event' + data.sensorid,
                Sensor__c = sensor.Id,
                X_Number__c = vector.x,
                Y_Number__c = vector.y,
                Z_Number__c = vector.z
            );
            sensorEvents.add(event);
        }
        insert sensorEvents;
    }
}